import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import { ConfigProvider } from 'antd';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ConfigProvider
        theme={{
          token: {
            colorPrimary: '#102C57',
          },
        }}>
        <body className={inter.className}>{children}</body>
      </ConfigProvider>
    </html>
  );
}
